export const slides = [
    {
      id: 1,
      src: "/images/banners/banner1@3x.png",
      alt: "Ai Drawing",
    },
    {
      id: 2,
      src: "/images/banners/banner2@3x.png",
      alt: "Anime Wallpaper",
    },
    {
      id: 3,
      src: "/images/banners/banner3@3x.png",
      alt: "Color Ease",
    },
    {
      id: 4,
      src: "/images/banners/banner4@3x.png",
      alt: "Ai Art Generator",
    },
    {
      id: 5,
      src: "/images/banners/banner5@3x.png",
      alt: "Phone Editor",
    },
    {
      id: 6,
      src: "/images/banners/banner6@3x.png",
      alt: "ScanXpert",
    },
    {
      id: 7,
      src: "/images/banners/banner7@3x.png",
      alt: "Video Editor",
    },
    {
      id: 8,
      src: "/images/banners/banner8@3x.png",
      alt: "Phone Tracker",
    },
    {
      id: 9,
      src: "/images/banners/banner9@3x.png",
      alt: "Docs Scan",
    },
    {
      id: 10,
      src: "/images/banners/banner10@3x.png",
      alt: "PDF reader",
    },
  ];

export const productItems = [
  {
    id: 1,
    src: "/images/product/paintByNumber.png",
    alt: "ColorEase: Paint By Number",
    title: "ColorEase: Paint By Number",
    downloadNumbers: "50K +",
    rate: 4.6,
    linkGooglePlay: "https://play.google.com/store/apps/details?id=com.ichime.color.ease.paint.by.number.coloring.book",
    linkAppStore: "",
  },
  {
    id: 2,
    src: "/images/product/aiDrawing.png",
    alt: "AR Drawing: Sketch & Paint",
    title: "AR Drawing: Sketch & Paint",
    downloadNumbers: "50K +",
    rate: 4.6,
    linkGooglePlay: "https://play.google.com/store/apps/details?id=com.triple.ar.drawing.art.design.picture",
    linkAppStore: "",
  },
  {
    id: 3,
    src: "/images/product/photoEditor.png",
    alt: "Ichime Perfect Photo Editor",
    title: "Ichime Perfect Photo Editor",
    downloadNumbers: "50K +",
    rate: 4.6,
    linkGooglePlay: "https://play.google.com/store/apps/details?id=com.ichime.dev.photo.editor.collage.maker",
    linkAppStore: "",
  },
  {
    id: 4,
    src: "/images/product/videoEditor.png",
    alt: "Video Editor & Maker - Ichime",
    title: "Video Editor & Maker - Ichime",
    downloadNumbers: "50K +",
    rate: 4.6,
    linkGooglePlay: "https://play.google.com/store/apps/details?id=com.ichime.dev.video.editor.maker",
    linkAppStore: "",
  },
  {
    id: 5,
    src: "/images/product/animeLiveWallpaper.png",
    alt: "Anime Live, 3D, 4K Wallpaper",
    title: "Anime Live, 3D, 4K Wallpaper",
    downloadNumbers: "50K +",
    rate: 4.6,
    linkGooglePlay: "https://play.google.com/store/apps/details?id=com.ichime.dev.anime.wallpaper",
    linkAppStore: "",
  },
  {
    id: 6,
    src: "/images/product/aiArtGen.png",
    alt: "Ichime - AI Art Generator",
    title: "Ichime - AI Art Generator",
    downloadNumbers: "50K +",
    rate: 4.6,
    linkGooglePlay: "https://play.google.com/store/apps/dev?id=6498748123207845551&pli=1",
    linkAppStore: "",
  },
  {
    id: 7,
    src: "/images/product/sleepSoundDream.png",
    alt: "Sleep Sound Dreams",
    title: "Sleep Sound Dreams",
    downloadNumbers: "50K +",
    rate: 4.6,
    linkGooglePlay: "https://play.google.com/store/apps/details?id=com.triple.relaxingsleepsound",
    linkAppStore: "",
    canHideMd: true,
  },
  {
    id: 8,
    src: "/images/product/aiCaloriesTracker.png",
    alt: "AI Track Calorie & Nutrition",
    title: "AI Track Calorie & Nutrition",
    downloadNumbers: "50K +",
    rate: 4.6,
    linkGooglePlay: "https://play.google.com/store/apps/details?id=com.ichime.dev.calories.tracker",
    linkAppStore: "",
    canHideMd: true,
  },
  {
    id: 9,
    src: "/images/product/pdfReaderViewer.png",
    alt: "PDF Reader - PDF Viewer",
    title: "PDF Reader - PDF Viewer",
    downloadNumbers: "50K +",
    rate: 4.6,
    linkGooglePlay: "https://play.google.com/store/apps/details?id=com.ichime.dev.pdf.viewer.preview.create",
    linkAppStore: "",
    canHide: true
  },
  {
    id: 10,
    src: "/images/product/docScan.png",
    alt: "Document Scanner - PDF Creator",
    title: "Document Scanner - PDF Creator",
    downloadNumbers: "50K +",
    rate: 4.6,
    linkGooglePlay: "https://play.google.com/store/apps/details?id=com.triple.camera.scanner.finance.calculator",
    linkAppStore: "",
    canHide: true
  },
  {
    id: 11,
    src: "/images/product/scanExpert.png",
    alt: "ScanXpert - QR Code & Barcode",
    title: "ScanXpert - QR Code & Barcode",
    downloadNumbers: "50K +",
    rate: 4.6,
    linkGooglePlay: "https://play.google.com/store/apps/details?id=com.ichime.dev.qr.scanner.pro",
    linkAppStore: "",
    canHide: true
  },
  {
    id: 12,
    src: "/images/product/voiceChange.png",
    alt: "Voice Changer - Voice Effects",
    title: "Voice Changer - Voice Effects",
    downloadNumbers: "50K +",
    rate: 4.6,
    linkGooglePlay: "https://play.google.com/store/apps/details?id=com.ichime.dev.voice.changer.voice.effect",
    linkAppStore: "",
    canHide: true
  },
  {
    id: 13,
    src: "/images/product/phoneTracker.png",
    alt: "Find My Phone - Phone Tracker",
    title: "Find My Phone - Phone Tracker",
    downloadNumbers: "50K +",
    rate: 4.6,
    linkGooglePlay: "https://play.google.com/store/apps/details?id=com.triple.phonetracker.gpslocation.phonelocation",
    linkAppStore: "",
    canHide: true
  },
];

export const testimonials = [
  {
    id: 1,
    src: "/images/testimonials/sarah.png",
    alt: "_ Sarah L., Teacher",
    name: "_ Sarah L., Teacher",
    content: "“I used to be intimidated by creating art, but ichime's PaintbyNumber and AI Art Generator have completely changed that! Now I can relax and create beautiful pieces, even if I don't have any artistic experience. It's a great way to express myself and unwind after a long day.”",
  },
  {
    id: 2,
    src: "/images/testimonials/david.png",
    alt: " _ David C., Entrepreneur",
    name: " _ David C., Entrepreneur",
    content: "“Ichime's DocScanner and PDF Reader are lifesavers for my business. I can scan important documents on the go and easily access them on any device. Plus, the editing features in the PDF Reader are incredibly helpful. No more scrambling to find a computer to work on my files.”",
  },
  {
    id: 3,
    src: "/images/testimonials/emily.png",
    alt: "_ Emily J., Photographer",
    name: "_ Emily J., Photographer",
    content: "“I used to struggle with using editing apps; however, Ichime's Photo Editor and Video Editor make things easier than ever. They offer a wide range of gorgeous filters, collage image templates and body shaping tools that are easy to use, yet the result turns out professional. Plus, the Voice Changer adds a fun twist to my videos!”",
  },
  {
    id: 4,
    src: "/images/testimonials/michael.png",
    alt: "_ Michael H., Fitness Enthusiast",
    name: "_ Michael H., Fitness Enthusiast",
    content: "“Calorie Tracker has been a game-changer for my health goals. It helps me stay mindful of what I'm eating and motivates me to make healthier choices. The app is easy to use and integrates with my fitness routine. Especially, it counts the amount of water I take in everyday and reminds me of drinking.”",
  },
  {
    id: 5,
    src: "/images/testimonials/anna.png",
    alt: "_ Anna K., Student.",
    name: "_ Anna K., Student.",
    content: "“Ichime is a wonderful studio for all my daily app needs. From editing photos and documents to creating art and tracking my health, they have an app for everything. The user interface is intuitive and friendly, and the apps service are all very reliable.The paying process is easy and smooth with various methods. The average price is inexpensive so I can buy as many filters as I want. Highly recommend!”",
  },
];